import { BaseSeeder } from '@adonisjs/lucid/seeders'
import ProjectProposal from '#models/project_proposal'

/**
 * Seed 7 đề xuất đề tài mẫu với các trạng thái khác nhau (theo prompt 07).
 * owner_id 6 = NCV (Khoa CNTT), 7 = CNDT (Khoa Kinh tế) từ user_seeder.
 */
const proposals = [
  {
    code: 'ĐT-2025-001',
    title: 'Nghiên cứu ứng dụng AI trong chẩn đoán bệnh lý hình ảnh y khoa',
    field: 'Công nghệ thông tin',
    level: 'TRUONG' as const,
    year: 2025,
    durationMonths: 18,
    keywords: ['AI', 'Deep Learning', 'Y khoa', 'Chẩn đoán hình ảnh'],
    ownerId: 6,
    ownerName: 'Nguyễn Văn A',
    ownerEmail: 'ncv@university.edu.vn',
    ownerUnit: 'Khoa CNTT',
    coAuthors: ['PGS.TS. Trần Minh Hoàng', 'ThS. Lê Thị Mai'],
    objectives: 'Phát triển hệ thống AI hỗ trợ chẩn đoán bệnh lý từ ảnh X-quang và CT scan.',
    summary: 'Đề tài tập trung nghiên cứu và phát triển thuật toán deep learning ứng dụng trong chẩn đoán hình ảnh y khoa.',
    contentOutline: '1. Tổng quan về AI trong y khoa\n2. Thu thập và xử lý dữ liệu\n3. Xây dựng mô hình\n4. Đánh giá và triển khai',
    expectedResults: 'Bộ dữ liệu ảnh y khoa chuẩn hóa; Mô hình AI đạt độ chính xác > 90%; 02 bài báo khoa học quốc tế.',
    applicationPotential: 'Ứng dụng trong các bệnh viện, phòng khám để hỗ trợ chẩn đoán nhanh và chính xác.',
    requestedBudgetTotal: 450000000,
    requestedBudgetDetail: 'Chi phí nhân sự: 200tr\nThiết bị: 150tr\nVật tư: 50tr\nCông bố khoa học: 50tr',
    status: 'SUBMITTED' as const,
    unitComment: null,
    unitApproved: null,
    sciDeptComment: null,
    sciDeptPriority: null,
  },
  {
    code: 'ĐT-2025-002',
    title: 'Đánh giá hiệu quả mô hình kinh tế tuần hoàn',
    field: 'Kinh tế - Quản lý',
    level: 'TRUONG' as const,
    year: 2025,
    durationMonths: 12,
    keywords: ['Kinh tế tuần hoàn', 'Bền vững'],
    ownerId: 7,
    ownerName: 'Trần Văn B',
    ownerEmail: 'cndt@university.edu.vn',
    ownerUnit: 'Khoa Kinh tế',
    coAuthors: [],
    objectives: 'Đánh giá hiệu quả mô hình kinh tế tuần hoàn tại các doanh nghiệp vừa và nhỏ.',
    summary: 'Nghiên cứu áp dụng mô hình kinh tế tuần hoàn và đánh giá hiệu quả thực tiễn.',
    contentOutline: null,
    expectedResults: null,
    applicationPotential: null,
    requestedBudgetTotal: 200000000,
    requestedBudgetDetail: null,
    status: 'UNIT_REVIEWED' as const,
    unitApproved: true,
    unitComment: 'Đề tài có ý nghĩa thực tiễn cao',
    sciDeptComment: null,
    sciDeptPriority: null,
  },
  {
    code: 'ĐT-2025-003',
    title: 'Phát triển hệ thống IoT giám sát nông nghiệp',
    field: 'Kỹ thuật - Công nghệ',
    level: 'CO_SO' as const,
    year: 2025,
    durationMonths: 24,
    keywords: ['IoT', 'Nông nghiệp'],
    ownerId: 6,
    ownerName: 'Nguyễn Văn A',
    ownerEmail: 'ncv@university.edu.vn',
    ownerUnit: 'Khoa CNTT',
    coAuthors: [],
    objectives: 'Xây dựng hệ thống IoT giám sát môi trường và tưới tiêu trong nông nghiệp.',
    summary: 'Phát triển hệ thống cảm biến và phần mềm giám sát nông nghiệp thông minh.',
    contentOutline: null,
    expectedResults: null,
    applicationPotential: null,
    requestedBudgetTotal: 300000000,
    requestedBudgetDetail: null,
    status: 'DRAFT' as const,
    unitComment: null,
    unitApproved: null,
    sciDeptComment: null,
    sciDeptPriority: null,
  },
  {
    code: 'ĐT-2025-004',
    title: 'Nghiên cứu tác động của chuyển đổi số',
    field: 'Khoa học xã hội',
    level: 'TRUONG' as const,
    year: 2025,
    durationMonths: 18,
    keywords: ['Chuyển đổi số', 'Doanh nghiệp'],
    ownerId: 7,
    ownerName: 'Trần Văn B',
    ownerEmail: 'cndt@university.edu.vn',
    ownerUnit: 'Khoa Kinh tế',
    coAuthors: [],
    objectives: 'Nghiên cứu tác động của chuyển đổi số đến hoạt động doanh nghiệp.',
    summary: 'Đánh giá tác động chuyển đổi số trong bối cảnh kinh tế hiện đại.',
    contentOutline: null,
    expectedResults: null,
    applicationPotential: null,
    requestedBudgetTotal: 250000000,
    requestedBudgetDetail: null,
    status: 'APPROVED' as const,
    unitApproved: true,
    unitComment: 'Đề tài phù hợp, đề nghị phê duyệt.',
    sciDeptPriority: 'HIGH' as const,
    sciDeptComment: 'Đề tài có tính thời sự cao, đề nghị ưu tiên thực hiện.',
  },
  {
    code: 'ĐT-2025-005',
    title: 'Phân tích và dự báo biến động thị trường',
    field: 'Kinh tế - Quản lý',
    level: 'BO' as const,
    year: 2025,
    durationMonths: 12,
    keywords: ['Thị trường', 'Dự báo'],
    ownerId: 6,
    ownerName: 'Nguyễn Văn A',
    ownerEmail: 'ncv@university.edu.vn',
    ownerUnit: 'Khoa CNTT',
    coAuthors: [],
    objectives: 'Phân tích và dự báo biến động thị trường tài chính.',
    summary: 'Xây dựng mô hình dự báo biến động thị trường.',
    contentOutline: null,
    expectedResults: null,
    applicationPotential: null,
    requestedBudgetTotal: 180000000,
    requestedBudgetDetail: null,
    status: 'REJECTED' as const,
    unitApproved: false,
    unitComment: 'Đề tài thiếu tính khả thi',
    sciDeptComment: null,
    sciDeptPriority: null,
  },
  {
    code: 'ĐT-2025-006',
    title: 'Nghiên cứu phát triển vaccine thế hệ mới',
    field: 'Y - Dược',
    level: 'NHA_NUOC' as const,
    year: 2025,
    durationMonths: 36,
    keywords: ['Vaccine', 'Y học'],
    ownerId: 7,
    ownerName: 'Trần Văn B',
    ownerEmail: 'cndt@university.edu.vn',
    ownerUnit: 'Khoa Kinh tế',
    coAuthors: [],
    objectives: 'Nghiên cứu phát triển vaccine thế hệ mới phòng bệnh truyền nhiễm.',
    summary: 'Đề tài cấp Nhà nước về phát triển vaccine.',
    contentOutline: null,
    expectedResults: null,
    applicationPotential: null,
    requestedBudgetTotal: 2500000000,
    requestedBudgetDetail: null,
    status: 'SUBMITTED' as const,
    unitComment: null,
    unitApproved: null,
    sciDeptComment: null,
    sciDeptPriority: null,
  },
  {
    code: 'ĐT-2024-015',
    title: 'Đánh giá tác động của biến đổi khí hậu đến sản xuất lúa',
    field: 'Nông nghiệp - Sinh học',
    level: 'TRUONG' as const,
    year: 2024,
    durationMonths: 18,
    keywords: ['Biến đổi khí hậu', 'Lúa'],
    ownerId: 6,
    ownerName: 'Nguyễn Văn A',
    ownerEmail: 'ncv@university.edu.vn',
    ownerUnit: 'Khoa CNTT',
    coAuthors: [],
    objectives: 'Đánh giá tác động biến đổi khí hậu đến sản xuất lúa vùng đồng bằng.',
    summary: 'Nghiên cứu tác động khí hậu đến năng suất và chất lượng lúa.',
    contentOutline: null,
    expectedResults: null,
    applicationPotential: null,
    requestedBudgetTotal: 400000000,
    requestedBudgetDetail: null,
    status: 'APPROVED' as const,
    unitApproved: true,
    unitComment: 'Đề tài có ý nghĩa thực tiễn.',
    sciDeptPriority: 'HIGH' as const,
    sciDeptComment: 'Đề nghị ưu tiên triển khai.',
  },
]

export default class ProjectProposalSeeder extends BaseSeeder {
  async run() {
    for (const row of proposals) {
      const exists = await ProjectProposal.findBy('code', row.code)
      if (!exists) {
        await ProjectProposal.create(row)
      }
    }
  }
}
