import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Specialization from '#models/specialization'

/** Danh sách chuyên ngành (đã clean). */
const NAMES: string[] = [
  'Lý luận và Phương pháp dạy học',
  'Vật lý lý thuyết và Vật lý toán',
  'Khoa học Môi trường',
  'Toán Giải tích',
  'Đo lường và đánh giá trong giáo dục',
  'Kế toán tài chính',
  'Sinh thái học',
  'Công nghệ thông tin',
  'Sinh môi trường',
  'Quản lý Giáo dục',
  'Giáo dục Tiểu học',
  'Tài chính Ngân hàng',
  'Quản lý Kinh tế',
  'Hóa Hữu cơ',
  'Kế toán',
  'Địa lý',
  'Văn học Việt Nam',
  'Văn học',
  'Sinh - Môi trường',
  'Xây dựng cầu đường',
  'Cử nhân Kinh tế',
  'Luật kinh tế',
  'Địa lý học',
  'Kỹ thuật Điện tử - Tin học',
  'Việt Nam học (Định hướng ứng dung)',
  'Thư viện thông tin',
  'Khoa học giáo dục (Lý luận và Phương pháp dạy học bộ môn Lịch sử)',
  'Tiếng Nga',
  'Giáo dục Chính trị',
  'Điều dưỡng',
  'Sư phạm Mầm non',
  'Quản trị và kinh doanh quốc tế',
  'Phương pháp Toán Sơ cấp',
  'Khoa học Máy tính',
  'Toán học (Lý thuyết xác suất và thống kê toán học)',
  'Toán học (Đại số và Lý thuyết số)',
  'Toán học',
  'Khoa học giáo dục',
  'Giáo dục học',
  'Lý luận và Phương pháp dạy học Kỹ thuật',
  'Toán học (Toán Giải tích)',
  'Đại số và Lý thuyết số',
  'Khoa học (Phương pháp Toán Sơ cấp)',
  'Toán Lí (Phương trình Vi phân và Tích phân)',
  'Toán học (Toán ứng dụng)',
  'Xác suất thống kê',
  'Ngôn ngữ Thái',
  'Toán học tính toán',
  'Hệ thống thông minh',
  'Phương pháp dạy học Toán',
  'Khoa học Máy tính và Kỹ thuật',
  'Toán học mô hình',
  'Lý thuyết xác suất và thống kê',
  'Toán học lý thuyết',
  'Hệ thống điều khiển tự động hóa vi tính và Công nghệ thông tin cấp tiến',
  'Hóa phân tích',
  'Hóa lý thuyết và Hóa lý',
  'Công nghệ thực phẩm',
  'Hóa Vô cơ',
  'Kỹ thuật an toàn hệ thống hạt nhân',
  'Công nghệ hóa học',
  'Hóa học',
  'Kỹ thuật điện tử',
  'Vật lý chất rắn',
  'Điện hóa',
  'Lý luận và phương pháp dạy học bộ môn Vật lý',
  'Vật lý lý thuyết và vậy lý toán',
  'Khoa học và Quản lý môi trường',
  'Khoa học Vật liệu',
  'LL&PPDH Vật lý',
  'Vật lý lý thuyết',
  'Kỹ thuật công nghệ tích hợp Nano',
  'Vật lý',
  'Hóa lí thuyết và hóa lí (định hướng ứng dụng)',
  'Khoa học kỹ thuật',
  'Quang học',
  'LL$PPDH Bộ môn Vật lý',
  'Phương pháp giảng dạy Vật lý',
  'Vật lý nguyên tử',
  'Lịch sử Thế giới',
  'Viễn thám',
  'Công nghệ thực vật',
  'Công nghệ sinh học',
  'Quản lý tài nguyên và môi trường',
  'Công nghệ thực phẩm và đồ uống',
  'Tài nguyên thiên nhiên và phát triển bền vững',
  'Khoa học Nông nghiệp',
  'Sư phạm Tiếng Trung',
  'Lý luận và phương pháp dạy học bộ môn Sinh học',
  'Khoa học, Nông nghiệp và sự sống',
  'Vật Liệu hoạt tính sinh học',
  'Khoa học sự sống',
  'Hóa dược',
  'Khoa học môi trường và bảo vệ môi trường',
  'Khoa học và quản lý Biển và Hồ',
  'Sinh lý học thực vật',
  'Nghiên cứu Môi trường toàn cầu',
  'Lý luận và Phương pháp dạy học môn Toán',
  'Giáo dục Mầm non',
  'Lý luận và PPDH bộ môn Toán',
  'Sư phạm Ngữ văn',
  'Công nghệ hóa-sinh học',
  'Lý luận và Phương pháp dạy học bộ môn Toán',
  'Quản lý môi trường',
  'Ngôn ngữ học',
  'Lý luận và phương pháp dạy học Văn - Tiếng Việt',
  'Lý luận và lịch sử giáo dục',
  'Giáo dục học (Tiểu học)',
  'Vật lý Địa cầu',
  'Giáo dục học (Giáo dục Tiểu học)',
  'Lý luận và phương pháp dạy học bộ môn Toán học',
  'Phương pháp giảng dạy Sinh học',
  'Sinh lý người và động vật',
  'Lý luận văn học',
  'Giáo dục môi trường',
  'Thủy sinh vật học',
  'Tâm lý học lâm sàng trẻ em và vị thành niên',
  'Tâm lý học',
  'Công tác xã hội',
  'Tâm lý học phát triển và giáo dục',
  'Xã hội học',
  'Giáo dục Đại học',
  'Nhân học Văn hóa',
  'Quan hệ quốc tế',
  'Địa lý Kinh tế - Xã hội và quản lý không gian',
  'Lý luận và phương pháp dạy học bộ môn Lịch sử',
  'Lịch sử',
  'Khoa học giáo dục: Lý luận và phương pháp dạy học bộ môn Giáo dục Chính trị',
  'Quản lý đất đai',
  'Việt Nam học',
  'Địa lí tự nhiên',
  'Văn hóa học (tại Viện Văn hóa Nghệ thuật Việt Nam)',
  'Kinh tế chính trị',
  'Du lịch học',
  'Luật',
  'Du lịch',
  'Khoa học vùng: Kinh doanh và Lãnh thổ',
  'Lý luận và phương pháp dạy học bộ môn Giáo dục Chính trị',
  'Lịch sử Trung Quốc cổ đại',
  'Lịch sử Việt Nam',
  'Triết học',
  'Chính trị học',
  'Lý luận và Phương pháp dạy học bộ môn Địa lý',
  'Khoa học giáo dục (LL&PPDH Địa lý)',
  'Lịch sử học',
  'Luật hiến pháp và luật hành chính',
  'Quốc tế học',
  'Báo chí học',
  'Báo chí',
  'Lý luận ngôn ngữ',
  'Văn học Bắc Mỹ',
  'Giáo dục Thể chất - Giáo dục Quốc phòng',
  'Dân tộc học',
  'Văn học Nga',
  'Báo chí truyền thông',
  'Ngữ văn (Lí luận văn học)',
  'Ngôn ngữ',
  'Văn hóa học',
  'Hán Nôm',
  'Văn hóa Trung Quốc',
  'Lý luận và phương pháp dạy học bộ môn Văn - Tiếng Việt',
  'Nhân học',
  'Văn học nước ngoài',
  'Hệ thống thông tin',
  'Tiếng Anh',
  'Chọn giống và nhân giống cây nông nghiệp',
  'Sư phạm kỹ thuật Điện tử - Tin học',
  'Ngôn ngữ và Văn hóa nước ngoài',
  'Công nghệ thực phẩm - Sinh học',
  'Tài chính - Ngân hàng',
  'Động vật học',
  'Mỹ thuật',
  'Xây dựng công trình thủy',
  'Toán - Tin',
  'Xây dựng dân dụng và công nghiệp',
  'Cơ khí động lực',
  'Kế toán doanh nghiệp',
  'Tâm lý - Giáo dục',
  'Lý luận và Lịch sử Mỹ thuật',
  'Lý luận và phương pháp dạy học Âm nhạc',
  'Mỹ thuật tạo hình',
  'Lý luận và phương pháp giảng dạy âm nhạc',
  'Biểu diễn thanh nhạc',
  'Âm nhạc học',
  'Nghệ thuật thị giác',
  'Lý luận và phương pháp dạy học bộ môn Mỹ thuật',
  'Mỹ thuật (Nghệ thuật thị giác)',
  'Sư phạm Âm nhạc',
  'Quản lý trật tự xã hội',
  'Cử nhân Địa lý',
  'Kế toán tổng hợp',
  'Điện kỹ thuật',
  'Báo chí - c/n Báo phát thanh',
]

/** Bỏ dấu tiếng Việt + chuẩn hóa thành code (A-Z0-9 và gạch dưới). */
function toSlugCode(name: string): string {
  const base = name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
  return base.slice(0, 60) || 'CN'
}

/**
 * Seed danh mục chuyên ngành (danh sách đã clean).
 * - XÓA TOÀN BỘ dữ liệu cũ rồi nạp lại đúng theo NAMES (đồng bộ tuyệt đối).
 * - Code tự sinh từ tên (slug không dấu); nếu trùng thì thêm hậu tố _2, _3...
 */
export default class SpecializationSeeder extends BaseSeeder {
  async run() {
    // Xóa sạch dữ liệu cũ để đồng bộ đúng danh sách mới
    await Specialization.query().delete()

    const usedCodes = new Map<string, number>()

    for (let i = 0; i < NAMES.length; i++) {
      const name = NAMES[i]
      const baseCode = toSlugCode(name)

      const count = usedCodes.get(baseCode) ?? 0
      usedCodes.set(baseCode, count + 1)
      const code = count === 0 ? baseCode : `${baseCode}_${count + 1}`.slice(0, 80)

      await Specialization.create({
        code,
        name,
        displayOrder: (i + 1) * 10,
        status: 'ACTIVE',
      })
    }
  }
}
